### ISSUE TITLE
sh: 1: source: not found

### ISSUE THREAD

**Issue by al102964** [dataframehq/whale#118]
I can't manage to successfully execute a connection to a postgres database. I followed all the instructions specified at the website https://docs.whale.cx/ without success, I ran make && make rust  and make install_rust. At this point I have whale binary in ~/.whale/bin/whale location and I'm able to init my first data warehouse, however, when I try to execute wh pull, this error appears over and over again. I'm on a ubuntu 18.04 os. Thank you for your this project and for your time, hope you can help me. Seems to be a problem related to issue #113 
![image](https://user-images.githubusercontent.com/13053870/103030641-d4b80880-4521-11eb-9fe1-3c2568502263.png)

**Comment by biomunky** [comment]
I'm trying to work out what happened with #113 - I'm actually finding that I can't install whale on my mac with python 3.9!

**Comment by rsyi** [comment]
@biomunky  Yeah... unfortunately a bunch of libraries (pyarrow, in particular) just break with 3.9. It's terrible. After spending hours trying to get them to work, I had to just downgrade back to 3.8 (`brew info python@3.8` and follow instructions to add the Cellar installation to your path).

@al102964 I believe I found a fix for this (turns out `source` is a bash-specific term): https://github.com/dataframehq/whale/pull/119

Can you try again and let me know if this works?

**Comment by al102964** [comment]
Thank you very much @rsyi problem is solved now, I am able to collect metadata from my postgres data warehouse.
