### ISSUE TITLE
No option to use role in Snowflake connection configuration

### ISSUE THREAD

**Issue by dwallace0723** [dataframehq/whale#154]
Snowflake allows you to specify a role when establishing a connection. In our case, the only way data team members would be able to run the queries required by Whale is by assuming a specific role that has been granted to them. It would be nice to be able to specify a `role` in the connection configuration.

**Comment by rsyi** [comment]
Hey @dwallace0723 - sorry for the delay here. Just added support for this -- you just have to add a `role` entry in your `wh connections` yaml file. Haven't had a chance to add support to the `wh init` command yet. 😅

You'll have to update to the latest version of whale for this to work (if you're using macos, you can run `brew upgrade whale`, otherwise `git pull` and run `make && make install` again).

Let me know if you have any other trouble!
